apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    isDefault: true
    jsonData:
      version: Flux
      organization: iiot-org
      defaultBucket: iiot-bucket
      tlsSkipVerify: true
    secureJsonData:
      token: my-super-token
